on:
  push:
    branches: main

name: Render to HTML & Commit

jobs:
  render:
    name: Render to HTML & Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e "install.packages('rmarkdown')"
      - name: Install bookdown
        run: Rscript -e "install.packages('bookdown')"
      - name: Render Rmd to HTML
        run: Rscript -e "bookdown::render_book('src', 'bookdown::html_chapters')"
      - name: Move output to docs
        run: rm -rf docs && mv src/_book docs
      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: "docs"
          message: "Automatic: Update docs"
