name: Render to HTML
on:
  pull_request:

jobs:
  render:
    name: Render to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t mvaaltola/bookdown .
      - name: Render Rmd to HTML
        run: ./render.sh
      - name: Assert index.html exists
        run: test -f out/index.html
