name: Render to HTML & Deploy
on:
  repository_dispatch:
    types: [render-deploy]

jobs:
  render-deploy:
    name: Render to HTML & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t mvaaltola/bookdown .
      - name: Render Rmd to HTML
        run: ./render.sh
      - name: Rename output to docs
        run: rm -rf docs && mv out docs
      - name: Assert index.html exists
        run: test -f docs/index.html

      - name: Stash output
        run: git stash --all
      - name: Checkout branch gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Clean docs and apply stash
        run: rm -rf docs && git stash pop

      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          branch: "gh-pages"
          message: "Automatic: Update docs"
