name: Render to HTML & Deploy
on:
  repository_dispatch:
    types: [render-deploy]

jobs:
  render-deploy:
    name: Render to HTML & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e "install.packages('rmarkdown')"
      - name: Install bookdown
        run: Rscript -e "install.packages('bookdown')"

      - name: Render Rmd to HTML
        run: Rscript -e "bookdown::render_book('src', 'bookdown::html_chapters')"
      - name: Move output to docs
        run: rm -rf docs && mv src/_book docs

      - name: Stash output
        run: git stash --all
      - name: Checkout branch gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Clean docs and apply stash
        run: rm -rf docs && git stash pop

      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          branch: "gh-pages"
          message: "Automatic: Update docs"
